name: Node.js CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  new_job:
      runs-on: ubuntu-latest
    steps:
    - name: Git clone
      uses: actions/checkout@v3
    - name: Setup Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Run unit tests
      run: |
        npm install
        chmod u+x ./node_modules/.bin/*
        npm test
